#!/usr/bin/env python3
"""Generate a stand-in for the WPF XAML compiler's MainWindow.g.cs.

The real file is produced by PresentationBuildTasks, which only runs on Windows.
This reproduces the part code-behind depends on -- a field per named control and
an InitializeComponent -- so the whole plugin can be type-checked on any platform.

PIXMY4D-Nav has no MainWindow.xaml yet (the tool windows are deferred work --
see docs/work-orders/pixmy4d-nav.md tasks P3/P4). Until one exists this script
is a no-op that exits 0, so the verification harness stays runnable. When a
MainWindow.xaml is added, point XAML below at it and this behaves exactly like
the AutoNAV2/NavEx version it was adapted from: walking Name=/x:Name=
attributes, skipping ControlTemplate/DataTemplate subtrees (template-scoped
names are never promoted to code-behind fields in real WPF), typecheck.csproj
must then re-add obj/MainWindow.g.cs to its <Compile Include> list.
"""

import os
import sys
import xml.etree.ElementTree as ET

XAML_NS = "{http://schemas.microsoft.com/winfx/2006/xaml}"
TEMPLATE_TAGS = {"ControlTemplate", "DataTemplate", "ItemsPanelTemplate", "HierarchicalDataTemplate"}

# Every element type expected to carry a Name in MainWindow.xaml, once it exists.
WPF_TYPES = {
    "Window": "System.Windows.Window",
    "Grid": "System.Windows.Controls.Grid",
    "StackPanel": "System.Windows.Controls.StackPanel",
    "DockPanel": "System.Windows.Controls.DockPanel",
    "Border": "System.Windows.Controls.Border",
    "TextBlock": "System.Windows.Controls.TextBlock",
    "TextBox": "System.Windows.Controls.TextBox",
    "Button": "System.Windows.Controls.Button",
    "CheckBox": "System.Windows.Controls.CheckBox",
    "ComboBox": "System.Windows.Controls.ComboBox",
    "ComboBoxItem": "System.Windows.Controls.ComboBoxItem",
    "TabControl": "System.Windows.Controls.TabControl",
    "TabItem": "System.Windows.Controls.TabItem",
    "TreeView": "System.Windows.Controls.TreeView",
    "ProgressBar": "System.Windows.Controls.ProgressBar",
    "ScrollViewer": "System.Windows.Controls.ScrollViewer",
    "ListBox": "System.Windows.Controls.ListBox",
    "ListView": "System.Windows.Controls.ListView",
    "DataGrid": "System.Windows.Controls.DataGrid",
    "Slider": "System.Windows.Controls.Slider",
    "Label": "System.Windows.Controls.Label",
    "Expander": "System.Windows.Controls.Expander",
    "Image": "System.Windows.Controls.Image",
}

HERE = os.path.dirname(os.path.abspath(__file__))
XAML = os.path.join(HERE, "..", "..", "PIXMY4D-Nav", "MainWindow.xaml")
OUT_DIR = os.path.join(HERE, "obj")
OUT = os.path.join(OUT_DIR, "MainWindow.g.cs")


def walk(element, named, errors):
    tag = element.tag.split("}")[-1]
    if tag in TEMPLATE_TAGS:
        return  # separate NameScope -- not exposed as class fields
    name = element.get(XAML_NS + "Name") or element.get("Name")
    if name:
        if tag not in WPF_TYPES:
            errors.append((tag, name))
        else:
            named.append((name, WPF_TYPES[tag]))
    for child in element:
        walk(child, named, errors)


def main():
    if not os.path.exists(XAML):
        print("no MainWindow.xaml yet (tool windows are deferred work) -- skipping stub generation")
        return 0

    root = ET.parse(XAML).getroot()

    named = []
    errors = []
    walk(root, named, errors)
    if errors:
        for tag, name in errors:
            print("error: no type mapping for <%s Name=\"%s\">; "
                  "add it to WPF_TYPES" % (tag, name), file=sys.stderr)
        return 1

    fields = "\n".join("        internal %s %s;" % (t, n) for n, t in named)

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT, "w") as handle:
        handle.write(
            "// Generated by tools/typecheck/gen_xaml_stub.py -- do not edit.\n"
            "// Stands in for the WPF XAML compiler output so the plugin can be\n"
            "// type-checked without Windows/Navisworks. Not used by the real build.\n"
            "namespace PIXMY4D_Nav\n"
            "{\n"
            "    public partial class MainWindow : System.Windows.Window\n"
            "    {\n"
            "%s\n"
            "\n"
            "        public void InitializeComponent() { }\n"
            "    }\n"
            "}\n" % fields)

    print("generated %s with %d named controls" % (os.path.relpath(OUT), len(named)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
