using System;
using System.Collections.Generic;
using System.IO;
using PIXMYD_Nav.Core.Nwc;
using PIXMYD_Nav.Core.Points;

namespace PIXMYD_Nav
{
    /// <summary>
    /// The OBJ reader, which is the plugin's first mesh reader of any kind.
    ///
    /// It stands between a file somebody else wrote and a native API that
    /// crashes rather than complains, so the tests here are mostly about the
    /// parts of OBJ that are easy to get subtly wrong: one-based indices,
    /// negative indices, separate index streams per attribute, and the fact
    /// that two corners at one point can be two different vertices.
    /// </summary>
    internal static class ObjReaderTests
    {
        public static int Run()
        {
            int failures = 0;
            ReadsATriangleWithEverythingOnIt(ref failures);
            IndicesAreOneBasedAndMayCountBackwards(ref failures);
            SplitsAVertexWhenItsTextureCoordinatesDiffer(ref failures);
            FansAPolygonIntoTriangles(ref failures);
            RefusesWhatItCannotTurnIntoAMesh(ref failures);
            FindsTheAtlasThroughTheMaterialLibrary(ref failures);
            return failures;
        }

        private static ObjReader.Result Read(string text)
        {
            using (var reader = new StringReader(text))
                return ObjReader.Read(reader, "test");
        }

        private static void ReadsATriangleWithEverythingOnIt(ref int failures)
        {
            ObjReader.Result r = Read(string.Join("\n", new[] {
                "# generated by PIXMYD",
                "mtllib scan.mtl",
                "v 0 0 0 1.0 0.0 0.0",
                "v 1 0 0 0.0 1.0 0.0",
                "v 0 1 0 0.0 0.0 1.0",
                "vn 0 0 1",
                "vt 0.25 0.75",
                "vt 0.5 0.75",
                "vt 0.25 0.5",
                "usemtl scan-material",
                "f 1/1/1 2/2/1 3/3/1",
            }));

            Program.Check(r.Ok, "a complete triangle reads: " + r.Message, ref failures);
            if (!r.Ok) return;

            Program.Check(r.MaterialLibrary == "scan.mtl",
                "the material library is reported, got " + r.MaterialLibrary, ref failures);
            Program.Check(r.Mesh.TriangleCount == 1,
                "one face is one triangle, got " + r.Mesh.TriangleCount, ref failures);
            Program.Check(r.Mesh.Vertices.Count == 3,
                "three distinct corners are three vertices, got " + r.Mesh.Vertices.Count,
                ref failures);
            Program.Check(r.Mesh.HasNormals && r.Mesh.HasColors && r.Mesh.HasUvs,
                "normals, colours and UVs all survive", ref failures);

            Program.Check(Math.Abs(r.Mesh.Colors[1].Y - 1.0) < 1e-12,
                "the vertex-colour extension is read", ref failures);

            // OBJ's V axis points up from the bottom left; everything here
            // works top-down, so it is flipped once on the way in.
            Program.Check(Math.Abs(r.Mesh.Uvs[1] - 0.25) < 1e-12,
                "V is flipped on the way in, got " + r.Mesh.Uvs[1], ref failures);
        }

        /// <summary>
        /// Both index forms are in the spec and both are easy to get wrong in a
        /// way that only shows up on somebody else's file.
        /// </summary>
        private static void IndicesAreOneBasedAndMayCountBackwards(ref int failures)
        {
            ObjReader.Result oneBased = Read("v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 3");
            Program.Check(oneBased.Ok, "one-based indices read", ref failures);
            if (oneBased.Ok)
                Program.Check(Math.Abs(oneBased.Mesh.Vertices[0].X) < 1e-12,
                    "index 1 is the first vertex, not the second", ref failures);

            ObjReader.Result negative = Read("v 0 0 0\nv 1 0 0\nv 0 1 0\nf -3 -2 -1");
            Program.Check(negative.Ok, "negative indices read: " + negative.Message, ref failures);
            if (negative.Ok)
            {
                Program.Check(negative.Mesh.TriangleCount == 1, "and make a triangle", ref failures);
                Program.Check(Math.Abs(negative.Mesh.Vertices[0].X) < 1e-12,
                    "-3 of three vertices is the first", ref failures);
            }

            // Zero is not a valid OBJ index, and treating it as one would take
            // the vertex before the first.
            Program.Check(!Read("v 0 0 0\nv 1 0 0\nv 0 1 0\nf 0 1 2").Ok,
                "index zero is refused", ref failures);
            Program.Check(!Read("v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 4").Ok,
                "an index past the end is refused", ref failures);
        }

        /// <summary>
        /// The one that matters for a photographic atlas. Every triangle gets
        /// its own tile, so one position carries a different texture coordinate
        /// in each triangle it belongs to. Keying vertices on position alone
        /// merges them, and the texture comes out smeared across the seam.
        /// </summary>
        private static void SplitsAVertexWhenItsTextureCoordinatesDiffer(ref int failures)
        {
            ObjReader.Result r = Read(string.Join("\n", new[] {
                "v 0 0 0", "v 1 0 0", "v 0 1 0", "v 1 1 0",
                "vt 0 0", "vt 0.1 0", "vt 0 0.1",
                "vt 0.9 0.9", "vt 0.8 0.9", "vt 0.9 0.8",
                // Vertices 2 and 3 are in both faces, with different vt each time.
                "f 1/1 2/2 3/3",
                "f 2/4 4/5 3/6",
            }));

            Program.Check(r.Ok, "the two faces read: " + r.Message, ref failures);
            if (!r.Ok) return;

            Program.Check(r.Mesh.TriangleCount == 2, "two faces, two triangles", ref failures);
            // Four positions, but six distinct (v, vt) pairs.
            Program.Check(r.Mesh.Vertices.Count == 6,
                "a position with two texture coordinates is two vertices, got "
                    + r.Mesh.Vertices.Count, ref failures);
            Program.Check(r.Mesh.HasUvs, "and the UVs are per corner", ref failures);
        }

        private static void FansAPolygonIntoTriangles(ref int failures)
        {
            ObjReader.Result r = Read("v 0 0 0\nv 1 0 0\nv 1 1 0\nv 0 1 0\nf 1 2 3 4");
            Program.Check(r.Ok, "a quad reads: " + r.Message, ref failures);
            if (!r.Ok) return;
            Program.Check(r.Mesh.TriangleCount == 2,
                "a quad is two triangles, got " + r.Mesh.TriangleCount, ref failures);
            Program.Check(r.Mesh.Vertices.Count == 4,
                "and still four vertices, got " + r.Mesh.Vertices.Count, ref failures);
        }

        private static void RefusesWhatItCannotTurnIntoAMesh(ref int failures)
        {
            Program.Check(!Read("").Ok, "an empty file is refused", ref failures);
            Program.Check(!Read("v 0 0 0\nv 1 0 0\nv 0 1 0").Ok,
                "vertices with no faces are refused", ref failures);
            Program.Check(!Read("v 0 0\nf 1 1 1").Ok,
                "a vertex with two numbers is refused", ref failures);
            Program.Check(!Read("v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2").Ok,
                "a face with two corners is refused", ref failures);
            Program.Check(!ObjReader.ReadFile("no-such-file-anywhere.obj").Ok,
                "a missing file is refused rather than throwing", ref failures);
        }
        /// <summary>
        /// The atlas is found through the MTL, not by assuming a filename.
        ///
        /// This is what carries the photographic texture into the NWC: the
        /// material asset names an image file, and if nothing resolves that
        /// name the model comes out flat grey with all the geometry intact --
        /// which is exactly the failure that is hard to spot, because it looks
        /// like a mesh rather than like a bug.
        /// </summary>
        private static void FindsTheAtlasThroughTheMaterialLibrary(ref int failures)
        {
            string folder = Path.Combine(
                Path.GetTempPath(), "pixmyd-obj-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(folder);
            try
            {
                string obj = Path.Combine(folder, "capture.obj");
                string mtl = Path.Combine(folder, "capture.mtl");
                string png = Path.Combine(folder, "capture.png");
                File.WriteAllText(obj, string.Join(Environment.NewLine, new[] {
                    "mtllib capture.mtl",
                    "v 0 0 0", "v 1 0 0", "v 0 1 0",
                    "vt 0 0", "vt 1 0", "vt 0 1",
                    "usemtl capture-material",
                    "f 1/1 2/2 3/3",
                }));
                File.WriteAllText(mtl, string.Join(Environment.NewLine, new[] {
                    "newmtl capture-material", "Kd 1 1 1", "map_Kd capture.png",
                }));
                File.WriteAllBytes(png, new byte[] { 0x89, 0x50, 0x4E, 0x47 });

                ObjReader.Result r = ObjReader.ReadFile(obj);
                Program.Check(r.Ok, "the OBJ reads: " + r.Message, ref failures);
                if (!r.Ok) return;

                Program.Check(string.Equals(r.Mesh.TexturePath, png,
                                            StringComparison.OrdinalIgnoreCase),
                    "map_Kd resolves against the OBJ folder, got "
                        + (r.Mesh.TexturePath ?? "null"), ref failures);
                Program.Check(r.Mesh.HasTexture,
                    "coordinates plus an atlas is a textured mesh", ref failures);

                // map_Kd may carry options before the filename. Skipping them
                // wrongly takes "-s" as the image and finds nothing.
                File.WriteAllText(mtl, "newmtl m" + Environment.NewLine
                                     + "map_Kd -s 1 1 1 -o 0 0 0 capture.png");
                Program.Check(
                    ObjReader.TextureBeside(obj, "capture.mtl").Length > 0,
                    "the options before the filename are stepped over", ref failures);

                // A named image that is not there is not a texture. Handing
                // the path on anyway makes Navisworks fail to open a file we
                // could have known was missing.
                File.WriteAllText(mtl, "map_Kd somewhere-else.png");
                Program.Check(ObjReader.TextureBeside(obj, "capture.mtl") == "",
                    "an image that is not on disk is not reported", ref failures);

                Program.Check(ObjReader.TextureBeside(obj, "no-such.mtl") == "",
                    "a missing material library is not reported", ref failures);
                Program.Check(ObjReader.TextureBeside(obj, "") == "",
                    "an OBJ with no mtllib has no texture", ref failures);
            }
            finally
            {
                try { Directory.Delete(folder, true); } catch (Exception) { }
            }
        }
    }
}
